Fixed bug of not exporting dsc resources and issue with Invoke-DscResource compatability (Fixes #263)
vmware/dscr-for-vmware pull request #275
Opened 2020-09-10 14:50 UTC by KristiyanGK

### Changed
- Updated **VMware.vSphereDSC** module manifest contents by removing **FunctionsToExport**, **CmdletsToExport** and **AliasesToExport**.

### Removed
- Removed the required **PowerCLI** modules that are dependencies of the **VMware.vSphereDSC** module from RequiredModules.ps1

2020-09-11 06:09 UTC, dmilov requested changes

2020-09-11 06:09 UTC, dmilov commented on Source/VMware.vSphereDSC/RequiredModules.ps1
> +RequiredModules = @( )
It'd be better to comment those and put a comment above why this is commented out. What problems it is causing, what is the effect of not having them, reference to the doc with install instructions.

2020-09-11 07:20 UTC, SimeonGerginov requested changes

2020-09-11 07:20 UTC, SimeonGerginov commented on Source/VMware.vSphereDSC/VMware.vSphereDSC.psd1
> +RequiredModules = @()
Verify if the RequiredModules array needs to be modified here. From what I remember the build takes care to change the array contents with the modules defined in the **RequiredModules.ps1**.

2020-09-14 08:59 UTC, dmilov approved these changes

2020-09-14 10:48 UTC, SimeonGerginov approved these changes

2020-09-14 10:58 UTC, merged